"""create canvas table

Revision ID: ce5d3aac277d
Revises: a4bb2753cfd8
Create Date: 2025-07-30 14:01:46.848588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.database.types import GUID


# revision identifiers, used by Alembic.
revision: str = 'ce5d3aac277d'
down_revision: Union[str, None] = 'a4bb2753cfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canvases')
    # ### end Alembic commands ###
