"""Add context field to projects table

Revision ID: ef22e324a3d3
Revises: ce5d3aac277d
Create Date: 2025-07-31 13:52:15.608250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef22e324a3d3'
down_revision: Union[str, None] = 'ce5d3aac277d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'context')
    # ### end Alembic commands ###
